### ISSUE TITLE
$HOME/.tng-workspace not created

### ISSUE THREAD

**Issue by arocha7** [sonata-nfv/tng-sdk-project#25]
when creating a new workspace:

$ tng-workspace -w xpto
xpto/workspace.yml

and then creating a new project:

$ tng-project -p myprj
2018-06-28 16:24:48 u16acc-tng tngsdk.project.workspace[29807] ERROR Unable to load workspace descriptor '/home/ubuntu/.tng-workspace/workspace.yml'
Could not find a 5GTANGO workspace at the specified location

as a workaround, 
* the '- /tng-workspace' directory can be manually created and the 'workspace.yml' file copied to there
* include "-w xpto" in the command line

in the latest, there is also an error message:

$ tng-project -w xpto -p myprj
2018-06-28 16:29:04 u16acc-tng tngsdk.project.project[30756] INFO Creating project at myprj
Traceback (most recent call last):
  File "/usr/local/bin/tng-project", line 9, in <module>
    load_entry_point('tngsdk.project==0.9', 'console_scripts', 'tng-project')()
  File "/usr/local/lib/python3.5/dist-packages/tngsdk.project-0.9-py3.5.egg/tngsdk/project/project.py", line 431, in create_project
    proj.create_prj()
  File "/usr/local/lib/python3.5/dist-packages/tngsdk.project-0.9-py3.5.egg/tngsdk/project/project.py", line 108, in create_prj
    self._create_dirs()
  File "/usr/local/lib/python3.5/dist-packages/tngsdk.project-0.9-py3.5.egg/tngsdk/project/project.py", line 136, in _create_dirs
    self._create_vnfd(vnfd_path)
  File "/usr/local/lib/python3.5/dist-packages/tngsdk.project-0.9-py3.5.egg/tngsdk/project/project.py", line 148, in _create_vnfd
    shutil.copyfile(srcfile, vnfd_path)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/tngsdk.**project-0.9-py3.5.egg**/tngsdk/project/samples/vnfd-sample.yml'

ubuntu@u16acc-tng:~/tng-sdk-package$ sudo ls -l /usr/local/lib/python3.5/dist-packages/tngsdk*
total 8
drwxr-sr-x 2 root staff 4096 Jun 28 15:49 EGG-INFO
drwxr-sr-x 4 root staff 4096 Jun 28 15:49 tngsdk

**Comment by StefanUPB** [comment]
I think, what you're describing is intended behavior: If you call tng-project without specifying the location of your workspace, then it assumes the default workspace location, i.e., `~/.tng-workspace`. However, you installed the workspace at a different location by using `-w xpto` when calling tng-workspace. So now, when you use tng-project, you have to point it to the location of your workspace using `-w xpto`. Alternatively, you can just create the workspace at the default location, then you don't have to specify the location when calling tng-project (`-w`).

Does that solve the problem? I can update the error output to clarify.

**Comment by StefanUPB** [comment]
I made the error message a bit more expressive to indicate that the workspace location has to be specified with `-w`.

**Comment by arocha7** [comment]
Hi Stefan, thank you for the assertive explanation. This was a non-existing issue ☺
Best regards, Alberto

**Comment by arocha7** [comment]
false positive solved. thank you for the clear explanation.
