### ISSUE TITLE
Crashbug: werkzeufg.middleware not found

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/tng-sdk-project#79]
I re-executed the setup.py but I still get this.

Any advice?

```
tng-project -h
Traceback (most recent call last):
  File "/Users/manuel/tango/venv_tango_sdk/bin/tng-project", line 11, in <module>
    load_entry_point('tngsdk.project', 'console_scripts', 'tng-project')()
  File "/Users/manuel/tango/venv_tango_sdk/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/manuel/tango/venv_tango_sdk/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/Users/manuel/tango/venv_tango_sdk/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/Users/manuel/tango/venv_tango_sdk/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/manuel/tango/tng-sdk-project/src/tngsdk/project/__init__.py", line 36, in <module>
    from tngsdk import rest, cli
  File "/Users/manuel/tango/tng-sdk-project/src/tngsdk/rest.py", line 42, in <module>
    from werkzeug.middleware.proxy_fix import ProxyFix
ModuleNotFoundError: No module named 'werkzeug.middleware'
```

**Comment by mpeuster** [comment]
This commit killed it: https://github.com/sonata-nfv/tng-sdk-project/commit/99c145737ebc2564e28da304af513eef43379eec#diff-55d680e02cf2df9fb8d3c905de041432

**Comment by mpeuster** [comment]
Never mind, I think force updating `werkzeug` to `0.15.1` fixes it. This is probably why the CI passed.

I suggest to add >= 0.15.1 to the `setup.py`

**Comment by stefanbschneider** [comment]
Sorry, about that. I just got a deprecation warning not to use `from werkzeug.contrib.fixers import ProxyFix` anymore and change it to `werkzeug.middleware`. Forgot about setting the updated version in the requirements.
